spring:
  application:
    name: user-service
  cloud:
    discovery:
      enabled: true
    inetutils:
      preferred-networks: 127.0.0.1
      ignored-interfaces: ".*"
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true
    instance:
      prefer-ip-address: true
      hostname: localhost
      ip-address: 127.0.0.1
      instance-id: ${spring.application.name}:${server.port}
      appname: ${spring.application.name}
      secure-port-enabled: false
      non-secure-port-enabled: true
      lease-renewal-interval-in-seconds: 30
      lease-expiration-duration-in-seconds: 90
  security:
    user:
      name: ${USER_NAME}
      password: ${USER_PASSWORD}
  app:
    jwtSecret: ${JWT_SECRET}
    access:
      expiration-ms: ${JWT_ACCESS_EXPIRATION_MS:600000}
    refresh:
      expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000}

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # Flyway configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true
    out-of-order: false
    table: flyway_schema_history
    baseline-version: 0
    baseline-description: "Initial baseline"
    placeholders:
      uuid_type: UUID
      uuid_default: DEFAULT gen_random_uuid()

  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        use_sql_comments: false

server:
  port: ${SERVER_PORT:8081}
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  metrics:
    tags:
      application: "${spring.application.name}"
  tracing:
    enabled: false

springdoc:
  api-docs:
    enabled: true
  show-actuator: true
  use-management-port: false
  swagger-ui:
    path: /docs

logging:
  level:
    root: WARN
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.springframework.security: WARN
