spring:
  application:
    name: user-service
  cloud:
    discovery:
      enabled: true
    inetutils:
      preferred-networks: 127.0.0.1
      ignored-interfaces: ".*"
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true
    instance:
      prefer-ip-address: true
      hostname: localhost
      ip-address: 127.0.0.1
      instance-id: ${spring.application.name}:${server.port}
      appname: ${spring.application.name}
      secure-port-enabled: false
      non-secure-port-enabled: true
      lease-renewal-interval-in-seconds: 30
      lease-expiration-duration-in-seconds: 90

server:
  port: 8081

# Backblaze B2 Configuration
b2:
  endpoint: ${B2_ENDPOINT:https://s3.ams5.backblazeb2.com}
  key:
    id: ${B2_KEY_ID:}
  application:
    key: ${B2_APPLICATION_KEY:}
  bucket:
    name: ${B2_BUCKET_NAME:}
  public:
    cdn:
      base: ${PUBLIC_CDN_BASE:https://scholarai-papers.s3.ams5.backblazeb2.com}
